### ISSUE TITLE
Copyright Notices

### ISSUE THREAD

**Issue by ksuderman** [lapps/lapps.github.io#7]
Ensure copyright notices have been added to all source files.
- [x] api
- [x] core
- [x] serialization
- [x] vocabulary
- [x] discriminator

**Comment by ksuderman** [comment]
@marcverhagen this should be done for the Brandeis services as well.  I see some code is copyright @chunqishi These files should be changed so they are copyright Brandeis University.

This is actually quite easy to do.  I believe IntelliJ can insert copyright notices to source files, but anything that uses the Lappsgrid Maven parent pom (that is everything that I am aware of) can also use the ANC Maven plugin's `copyright` goal:
1. Create a file named COPYRIGHT with the text of the copyright notice that should be inserted at the top of each source file.
2. Run the command `mvn anc:copyright` in the project root.

**Comment by chunqishi** [comment]
Hi, Marc,

I will double check the copyright things.
Could help me prepare a copyright txt, so that I could update the github
projects.

Best,




--
Chunqi Shi, Ph.D.
Research Scientist,
Department of Computer Science
110 Volen Center for Complex Systems,
Brandeis University,
415 South Street,
Waltham, MA 02454, USA

(tel) +1-781-736-2744
(email) shicq@cs.brandeis.edu

**Comment by keighrim** [comment]
Committed `core`, `discriminator`, `serialization`, `vocabulary` modules with update copyright notice.
